### ISSUE TITLE
Add information page when you visit the secret URL

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#130]
This should contain

- Views left
- Time left to view the secret
- Other information if available

**Comment by blazenn2** [comment]
Hello!

I am new to contributing to open-source projects and I want to resolve this issue. Can you please assign me this issue? Thank you :)

**Comment by bjarneo** [comment]
Sure. Go for it, and thanks! @blazenn2 

Feel free to do the ux youd like for this, as long as it is easy to read. Library used is mantine.dev.

**Comment by m4-droid** [comment]
Hey! @bjarneo 
can you elaborate more on how you want this feature to be implemented.
since on secret URL views left is already there, time left is not present so do you want the time left to be shown same as view left or create button like some thing that will show the information or lead to separate page.
and also will it be better if views left decrease by 1 live when someone opens the secret.

**Comment by bjarneo** [comment]
Hi,

I think I will close this issue as it is really not needed. Thank you for participating 🥇
